### PR TITLE
Allocate 8MB minimum to stack for new server threads

### LINKED ISSUE #204: Multi-Master - rdbcompression seg faults
When running keydb 6.0.8-rc1 configured as multi-master with 6 nodes and `rdbcompression` enabled, the child processes for executing a BGSAVE segfaults causing replication to fail. 

I am compiling from source and building this into an Alpine container, so I may have missed a dependency somewhere but I can't tell.

Disabling this feature causes everything to work as expected. 

**To Reproduce**
Setup 6 keydb processes in a full mesh, multi-master mode with `rdbcompression` enabled.

** Log Files **
Core Dump

```
/ # gdb /opt/keydb/keydb-server core.98
GNU gdb (GDB) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-alpine-linux-musl".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /opt/keydb/keydb-server...
[New LWP 98]

warning: Can't read pathname for load map: No error information.
Core was generated by `keydb-server /etc/keydb/keydb.conf'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  lzf_compress (in_data=in_data@entry=0x55c1904f42d4 <GlobalHidden::server+11892>, in_len=in_len@entry=40, out_data=out_data@entry=0x55c191cf3830, out_len=out_len@entry=36) at lzf_c.c:146
146	lzf_c.c: No such file or directory.
```

Key DB Logs repeat these messages:

```
15:20:S 18 Jun 2020 14:51:56.904 * Background saving started by pid 844
15:20:S 18 Jun 2020 14:51:57.000 # Background saving terminated by signal 11
15:20:S 18 Jun 2020 14:51:57.000 # Connection with replica 10.0.0.1:6379 lost.
15:20:S 18 Jun 2020 14:51:57.000 # SYNC failed. BGSAVE child returned an error
15:20:S 18 Jun 2020 14:51:57.907 * Replica 10.0.0.1:6379 asks for synchronization
15:20:S 18 Jun 2020 14:51:57.907 * Full resync requested by replica 10.0.0.1:6379
15:20:S 18 Jun 2020 14:51:57.907 * Starting BGSAVE for SYNC with target: disk
15:20:S 18 Jun 2020 14:51:57.907 * Background saving started by pid 845
15:20:S 18 Jun 2020 14:51:58.003 # Background saving terminated by signal 11
15:20:S 18 Jun 2020 14:51:58.003 # Connection with replica 10.0.0.1:6379 lost.
15:20:S 18 Jun 2020 14:51:58.003 # SYNC failed. BGSAVE child returned an error
```

Thanks for the help!

### PR DESCRIPTION
**Pull request by christianEQ**
New server threads need reasonable memory for LZF compression's hash table. This will allocate 8MB minimum, which is the default on Ubuntu. Fixes #204.

### CODE REVIEW

**Comment by JohnSully** [comment]
Needs a description of the problem and what the fix accomplishes. Commit message needs to reference the issue being fixed.

File: src/server.cpp [hunk 1]
```diff
@@ -5788,9 +5788,13 @@ int main(int argc, char **argv) {
     setOOMScoreAdj(-1);
     serverAssert(cserver.cthreads > 0 && cserver.cthreads <= MAX_EVENT_LOOPS);
     pthread_t rgthread[MAX_EVENT_LOOPS];
+
+    pthread_attr_t tattr;
+    pthread_attr_init(&tattr);
+    pthread_attr_setstacksize(&tattr, 1 << 23);
```
Comment (JohnSully) [inline src/server.cpp:5794]: Give a comment on the size in MB
